/* ══════════════════════════════════════════════════════════════
   기준 데이터 — 실제 사업장으로 교체할 때 이 파일만 수정하세요.
   Reference data — edit this file only, to match your own sites.
   ══════════════════════════════════════════════════════════════ */

const COUNTRIES=[
  {code:'VNM',ko:'베트남',en:'Vietnam'}, {code:'NPL',ko:'네팔',en:'Nepal'};

const SITES=[
  {code:'TAS',country:'VNM',ko:'떤선',en:'Tan Son'},{code:'DTI',country:'NPL',ko:'다딩',en:'Dhading'};

/* 선택지 — 저장되는 값은 항상 한국어(시트 값과 일치). 화면 표기만 번역됩니다. */
const L={
  성별:['여','남'], 출생등록:['있음','없음','확인불가'],
  중복확인:['다른 아동입니다','같은 아동이라 등록을 중단합니다'],
  취학여부:['다니고있음','중단함','다닌적없음'],
  건강상태:['양호','장애'],
  /* 장애명은 여러 개를 함께 고를 수 있습니다 */
  장애명:['시각장애','청각장애','지체장애','자폐스펙트럼','다운증후군',
         '언어장애','지적장애','혈우병','정신·심리장애']
};
const MULTI=['장애명'];
const OPT_EN={
  성별:{'여':'Female','남':'Male'},
  출생등록:{'있음':'Yes','없음':'No','확인불가':'Cannot verify'},
  중복확인:{'다른 아동입니다':'Different child','같은 아동이라 등록을 중단합니다':'Same child — stop here'},
  취학여부:{'다니고있음':'Attending','중단함':'Dropped out','다닌적없음':'Never attended'},
  건강상태:{'양호':'Good','장애':'Has a disability'},
  장애명:{'시각장애':'Visual','청각장애':'Hearing','지체장애':'Physical',
         '자폐스펙트럼':'Autism spectrum','다운증후군':'Down syndrome','언어장애':'Speech',
         '지적장애':'Intellectual','혈우병':'Haemophilia','정신·심리장애':'Mental health'}
};

/* 아동마스터 시트 컬럼 순서 — 시트와 반드시 일치해야 합니다.
   이 목록을 고치면 구글 시트의 머리글도 똑같이 고쳐야 합니다. */
const MASTER_COLS=['아동코드','국가코드','사업장코드','연번','등록일','등록담당자',
'현지어이름','성별','생년월일','생년월일추정','출생등록','중복확인','중복확인메모',
'동거가족수','가족구성',
'취학여부','학교명','학년','건강상태','장애명','신장','체중',
'장래희망','좋아하는과목','좋아하는색깔','취미',
'보호자동의','아동동의','활용동의','동의서사진','대표사진','상태','본부검수일',
'본부검수자','종료일','종료사유','기록ID','전송일시'];

const PHOTO_COLS=['사진ID','아동코드','촬영일','사진유형','사진파일','촬영자','촬영기준확인','비고'];

const STEPS=['basic','photo','family','edu','story','consent'];

/* 본부 수신 서버 — 배포한 Apps Script 웹앱 주소와 전송키.
   여기에 미리 넣어두면 직원이 설정 화면에서 입력하지 않아도 됩니다.
   저장소가 공개(Public)라면 비워두세요. 키가 인터넷에 노출됩니다. */
const SERVER={url:'',key:''};

/* 관리자 페이지 기본 비밀번호 — 배포 전에 바꾸세요. 앱 안에서도 바꿀 수 있습니다. */
const ADMIN={pin:'2026'};

const S={
  appName:['해외결연 아동 신규수급','Child sponsorship intake'],
  noSite:['사업장 미선택','No site selected'],
  siteSuffix:['사업장',' field office'],
  bigText:['큰 글씨','Larger text'],
  offline:['오프라인 상태입니다. 등록은 그대로 진행하세요.','You are offline. Registration works as usual.'],

  setupEyebrow:['시작 설정','Setup'],
  setupTitle:['사업장과 담당자를<br>먼저 지정하세요','Choose your site<br>and enter your name'],
  setupLede:['아동코드는 여기서 고른 국가·사업장으로 자동 생성됩니다.',
             'Child codes are generated from the country and site you pick here.'],
  staff:['등록담당자 이름','Your name'],
  country:['국가','Country'],
  site:['사업장','Field office'],
  choose:['선택하세요','Select'],
  chooseCountryFirst:['국가를 먼저 선택하세요','Select a country first'],
  startSeq:['시작 연번','Starting number'],
  startSeqHint:['코드슬롯 시트에서 본인에게 배정된 구간의 첫 번호를 넣으세요. 사업장에 직원이 여러 명이면 구간을 나눠야 번호가 겹치지 않습니다.',
                'Enter the first number of the range assigned to you. When several staff work at one site, split the range so codes never collide.'],
  setupErr:['담당자, 국가, 사업장, 시작 연번(1~500)을 모두 입력하세요.',
            'Fill in your name, country, site and a starting number from 1 to 500.'],
  startBtn:['등록 시작하기','Start registering'],

  homeEyebrow:['신규수급 · Child intake','Child intake'],
  homeTitle:['오늘 만난 아동을<br>등록하세요','Register the children<br>you met today'],
  nextCode:['다음 발급 번호는','Next code is'],
  statSaved:['이 기기 저장','Saved on device'],
  statLeft:['남은 번호','Codes left'],
  statPending:['미내보냄','Not exported'],
  newChild:['＋ 아동 등록 시작','＋ Register a child'],
  exportBtn:['내보내기','Export'],
  importBtn:['기존 명단 불러오기 (중복 대조)','Load existing roster (for duplicate check)'],
  rosterLoaded:['본부 명단 %n명 · %d 불러옴','%n children from HQ · loaded %d'],
  rosterClear:['명단 지우기','Clear roster'],
  rosterCleared:['불러온 명단을 지웠습니다.','Roster cleared.'],
  changeSetup:['사업장·담당자 변경','Change site or staff'],
  recordList:['등록 내역','Registered'],
  emptyList:['아직 등록한 아동이 없습니다.','No children registered yet.'],
  tagOut:['내보냄','Exported'],
  tagPend:['미내보냄','Pending'],
  warnPending:['아직 시트에 옮기지 않은 등록이 <b>%n건</b> 있습니다. 인터넷이 되는 곳에서 <b>내보내기</b>를 하세요.',
               '<b>%n</b> registrations have not been moved to the sheet yet. Export them where you have internet.'],
  warnOk:['모든 등록을 내보냈습니다.','Everything has been exported.'],
  warnPend2:['본부로 보내지 않은 등록이 <b>%n건</b> 있습니다. 인터넷이 되는 곳에서 <b>본부로 전송</b>을 눌러주세요.',
             '<b>%n</b> registrations have not been sent to HQ. Tap <b>Send to HQ</b> where you have internet.'],
  warnOk2:['모든 등록을 본부로 보냈습니다.','Everything has been sent to HQ.'],
  hqNotSet:['본부 전송 주소가 설정되지 않았습니다. 설정 화면에서 입력하세요.',
            'No HQ address is set. Enter it in the settings screen.'],
  seqFull:['이 사업장의 500개 번호를 모두 사용했습니다.','All 500 codes for this site are used.'],
  noRecords:['등록된 아동이 없습니다.','No children to export.'],

  resumeTitle:['작성 중이던 아동이 있습니다','You have an unfinished registration'],
  resumeBody:['%c · %s 단계까지 입력되어 있습니다. 이어서 작성하시겠어요?',
              'Saved at step %s for %c. Continue where you left off?'],
  resumeGo:['이어서 작성','Continue'],
  resumeDrop:['버리기','Discard'],
  drafted:['작성 중이던 내용을 버렸습니다.','Draft discarded.'],
  autosaved:['자동 저장됨','Saved'],

  back:['← 이전','← Back'],
  next:['다음 →','Next →'],
  finish:['등록 완료','Finish'],
  stepOf:['STEP %a / %b','STEP %a / %b'],

  st_basic:['기본 정보','Basic details'],
  st_basic_l:['출생증명서가 있으면 그대로 옮겨 적으세요. 여기서 중복 등록 여부를 먼저 확인합니다.',
              'Copy from the birth certificate where you have one. Duplicates are checked at this step.'],
  st_photo:['아동 사진','Child photo'],
  st_photo_l:['결연자에게 가장 먼저 보이는 사진입니다. 촬영 기준을 지켜주세요.',
              'This is the first thing a sponsor sees. Follow the photo standards.'],
  st_family:['가정 환경','Household'],
  st_family_l:['결연 필요도를 판단하는 근거가 됩니다.','This is the basis for judging need.'],
  st_edu:['교육과 건강','School and health'],
  st_edu_l:['학교에 다니는지, 어떤 도움이 필요한지 확인합니다.',
            'Whether the child is in school, and what help is needed.'],
  st_story:['아동 소개','About the child'],
  st_story_l:['결연자가 읽을 프로필 문구가 됩니다.','This becomes the profile the sponsor reads.'],
  st_consent:['동의 확인과 검토','Consent and review'],
  st_consent_l:['보호자 동의 없이는 등록할 수 없습니다.','Registration is not possible without guardian consent.'],

  assigned:['배정된 아동코드','Assigned child code'],
  assignedNote:['이 코드로 사진 파일명과 사진ID가 자동 생성됩니다.',
                'Photo filenames and photo IDs are generated from this code.'],
  localName:['아동 이름 (현지어)','Child\u2019s name'],
  localNamePh:['현지 표기 그대로','As written locally'],
  localNameHint:['출생증명서가 있으면 그 표기를 그대로 옮겨 적으세요. 이 이름으로 중복 등록을 확인합니다.',
                 'Copy the spelling from the birth certificate where there is one. Duplicates are checked by this name.'],
  engName:['영문 이름','Name in English'],
  engNameHint:['출생증명서 표기와 동일하게 입력하세요.','Match the spelling on the birth certificate.'],
  dob:['생년월일','Date of birth'],
  dobEst:['출생등록이 없어 <b>추정 생년월일</b>입니다 (보호자 진술 기준)',
          'No birth record — this is an <b>estimated date</b>, based on the guardian.'],
  birthReg:['출생등록증 보유','Birth certificate'],
  sex:['성별','Sex'],

  dupStrong:['⚠ 이미 등록된 아동과 일치합니다','⚠ Matches a child already registered'],
  dupStrongBody:['이름·생년월일·성별이 모두 같은 아동이 %n명 있습니다. 아래를 확인하고 같은 아이인지 판단하세요.',
                 '%n children have the same name, date of birth and sex. Check below and decide whether this is the same child.'],
  dupWeak:['같은 생년월일의 아동이 있습니다','A child with the same date of birth exists'],
  dupWeakBody:['같은 사업장에 생년월일이 같은 아동이 %n명 있습니다. 형제자매나 쌍둥이인지 확인하세요.',
               '%n children at this site share this date of birth. Check whether they are siblings or twins.'],
  dupResult:['확인 결과','Your decision'],
  dupNote:['판단 근거','Reason'],
  dupNoteHint:['무엇을 보고 다른 아동이라고 판단했는지 적어주세요. 본부 검수 때 근거가 됩니다.',
               'Write what made you conclude this is a different child. HQ reviews this.'],
  dupNotePh:['예: 사진 확인함. 쌍둥이 동생이며 보호자 진술로 확인',
             'e.g. Checked the photo. Twin sibling, confirmed by the guardian.'],
  dupErrPick:['기존 아동을 확인하고 결과를 선택하세요.','Check the existing record and choose a result.'],
  dupErrNote:['판단 근거를 적어주세요.','Write your reason.'],
  dupStop:['같은 아동이므로 등록을 중단합니다. 기존 코드를 사용하세요.',
           'Same child — registration stopped. Use the existing code.'],
  srcHq:['본부 명단','HQ roster'],
  srcDev:['이 기기','This device'],
  noPhoto:['사진<br>없음','No<br>photo'],
  yrs:['세','yrs'],

  shotFace:['상반신 사진 촬영','Take an upper-body photo'],
  shotFaceSub:['필수 · 대표사진으로 사용','Required · used as the main photo'],
  shotFull:['전신 사진 (선택)','Full-body photo (optional)'],
  shotFullSub:['생활 환경이 함께 보이면 좋습니다','Helpful when the surroundings are visible'],
  shotCons:['서명된 동의서 촬영','Photograph the signed consent form'],
  shotConsSub:['필수 · 원본은 사업장 보관','Required · keep the paper at the office'],
  retake:['다시 찍기','Retake'],
  guideTitle:['촬영 기준 확인','Photo standards'],
  guideSub:['모두 확인해야 다음으로 넘어갑니다.','All must be checked to continue.'],
  g_solo:['아동 혼자 있는 사진인가요? (다른 아동·성인 미포함)',
          'Is the child alone in the photo? (no other children or adults)'],
  g_face:['얼굴이 정면으로, 눈이 가려지지 않게 나왔나요?','Is the face front-on, with the eyes unobstructed?'],
  g_light:['그늘이나 실내 밝은 곳에서 찍었나요? (역광 금지)',
           'Taken in shade or good indoor light? (never against the sun)'],
  g_dress:['평상시 옷차림이며, 노출이 없나요?','Everyday clothing, nothing revealing?'],
  g_bg:['배경에 집 주소·학교명·차량번호가 보이지 않나요?',
        'No home address, school name or vehicle plate visible in the background?'],
  safeguard:['<b>아동보호 원칙</b><br>아동이 촬영을 원하지 않으면 찍지 않습니다. 아동을 불쌍하거나 무력하게 보이도록 연출하지 마세요.',
             '<b>Child safeguarding</b><br>If the child does not want to be photographed, do not photograph. Never pose a child to look pitiful or helpless.'],
  errFace:['상반신 사진을 촬영해 주세요.','Take the upper-body photo.'],
  errGuide:['촬영 기준을 모두 확인해 주세요.','Confirm every photo standard.'],
  errCons:['서명된 동의서를 촬영해 주세요.','Photograph the signed consent form.'],
  errConsent:['동의 항목을 모두 확인해 주세요.','Confirm every consent item.'],
  errRequired:['필수 항목입니다.','Required.'],
  errFix:['표시된 항목을 먼저 확인해 주세요.','Check the highlighted fields first.'],

  guardian:['주 보호자','Main carer'],
  household:['함께 사는 가족 수','People in the household'],
  familyMake:['가족 구성','Who lives with the child'],
  familyMakeHint:['아동과 함께 사는 사람을 적어주세요.','List the people living with the child.'],
  familyMakePh:['어머니, 아버지, 자매 2, 형제 1','Mother, father, 2 sisters, 1 brother'],
  schoolName:['학교명','School name'],
  schoolNamePh:['하와사 초등학교','Hawassa Primary School'],
  disability:['장애 유형','Type of disability'],
  disabilityHint:['해당하는 항목을 모두 골라주세요.','Choose every one that applies.'],
  height:['신장 (cm)','Height (cm)'],
  weight:['체중 (kg)','Weight (kg)'],
  color:['좋아하는 색깔','Favourite colour'],
  colorPh:['파랑','Blue'],
  errDisability:['장애 유형을 하나 이상 골라주세요.','Choose at least one type.'],
  errNumber:['숫자로 입력해 주세요.','Enter a number.'],
  income:['주 소득원','Main income'],
  water:['식수원','Drinking water'],
  waterHint:['식수와 전기는 생활 여건을 가장 잘 보여주는 지표입니다.',
             'Water and electricity say the most about living conditions.'],
  power:['전기','Electricity'],

  inSchool:['학교에 다니나요?','Is the child in school?'],
  grade:['학년','Grade'],
  gradePh:['초등 3학년','Grade 3'],
  noSchoolWhy:['다니지 않는 이유','Why not in school'],
  noSchoolHint:['학비, 거리, 노동, 돌봄, 장애 등','School fees, distance, work, caring duties, disability'],
  health:['건강 상태','Health'],
  healthNote:['건강 특이사항','Health notes'],
  healthHint:['진단명은 민감정보입니다. 지원에 꼭 필요한 내용만 적어주세요.',
              'A diagnosis is sensitive data. Write only what support decisions require.'],

  dream:['장래희망','Dream job'],
  dreamPh:['간호사','Nurse'],
  subject:['좋아하는 과목','Favourite subject'],
  subjectPh:['수학','Maths'],
  hobby:['취미','Hobby'],
  hobbyPh:['친구들과 축구하기','Playing football with friends'],
  childWords:['아동이 직접 한 말','The child\u2019s own words'],
  childWordsHint:['통역하되 바꾸지 마세요. 아동의 말투가 결연자에게 가장 큰 힘이 됩니다.',
                  'Translate, do not rewrite. The child\u2019s own voice matters most to the sponsor.'],
  childWordsPh:['저는 커서 아픈 사람을 돕고 싶어요.','I want to help sick people when I grow up.'],
  staffNote:['담당자 관찰 메모 (내부용)','Staff notes (internal)'],
  staffNoteHint:['결연자에게 공개되지 않습니다.','Never shown to the sponsor.'],

  previewEyebrow:['결연자에게 보이는 화면','What the sponsor will see'],
  profile:['결연 아동 프로필','Sponsored child profile'],
  noPhotoBox:['사진 없음','No photo'],
  noName:['이름 없음','No name'],
  blank:['미입력','Not filled in'],
  fDream:['꿈','Dream'],
  fSchool:['학교','School'],
  fFamily:['가족','Family'],
  fHealth:['건강','Health'],
  fWords:['아동의 말','In the child\u2019s words'],
  gapItem:['· %s이(가) 비어 있습니다','· %s is empty'],
  consentTitle:['동의 확인','Consent'],
  consentSub:['세 항목 모두 확인해야 등록이 완료됩니다.','All three are required to finish.'],
  c_guardian:['보호자가 결연 참여와 정보 제공에 <b>서면 동의</b>했습니다.',
              'The guardian has <b>signed consent</b> for sponsorship and data sharing.'],
  c_child:['아동에게 이해할 수 있는 말로 설명했고, 아동이 동의했습니다.',
           'The child was told in words they understand, and agreed.'],
  c_use:['사진과 정보가 결연자에게 전달된다는 점을 안내했습니다.',
         'They were told the photo and details go to a sponsor.'],
  saved:['%c 저장됨. 내보내기를 잊지 마세요.','%c saved. Remember to export.'],

  expEyebrow:['내보내기','Export'],
  expTitle:['시트에 옮기기','Move to the sheet'],
  expCount:['아동 %n명 · 사진 %p장','%n children · %p photos'],
  scopePending:['미내보낸 건만 (%n)','Not exported (%n)'],
  scopeAll:['전체 (%n)','Everything (%n)'],
  exp1:['1. 아동마스터.csv','1. children.csv'],
  exp1b:['구글 시트의 <b>아동마스터</b> 탭 2행부터 붙여넣으세요. 컬럼 순서가 시트와 동일합니다.',
         'Paste into the <b>아동마스터</b> tab from row 2. Column order matches the sheet.'],
  exp1c:['아동마스터.csv 내려받기','Download 아동마스터.csv'],
  exp2:['2. 사진.csv','2. photos.csv'],
  exp2b:['<b>사진</b> 탭 2행부터 붙여넣으세요. 아동코드로 자동 연결됩니다.',
         'Paste into the <b>사진</b> tab from row 2. It links by child code.'],
  exp2c:['사진.csv 내려받기','Download 사진.csv'],
  exp3:['3. 사진 파일','3. Photo files'],
  exp3b:['파일명이 사진 시트의 <b>사진파일</b> 값과 일치합니다. 압축을 풀어 드라이브 폴더에 그대로 올리세요.',
         'Filenames match the 사진파일 column. Unzip and upload the files to the Drive folder as they are.'],
  exp3c:['사진 %p장 내려받기 (ZIP)','Download %p photos (ZIP)'],
  exp4:['4. 내보냄으로 표시','4. Mark as exported'],
  exp4b:['위 세 가지를 모두 내려받고 시트에 붙여넣은 뒤 눌러주세요. 표시한 건은 목록에서 초록색으로 바뀝니다.',
         'Press this after you have downloaded all three and pasted them into the sheet. Marked items turn green in the list.'],
  exp4c:['%n건을 내보냄으로 표시','Mark %n as exported'],
  exp4done:['%n건을 내보냄으로 표시했습니다.','%n marked as exported.'],
  zipping:['사진을 묶는 중입니다…','Packing photos…'],
  backBtn:['← 돌아가기','← Back'],
  nothingPending:['미내보낸 건이 없습니다.','Nothing pending.'],

  impTitle:['기존 명단 불러오기','Load the existing roster'],
  impBody:['본부에서 받은 <b>아동마스터.csv</b>를 고르세요. 이 기기에 저장되어, 인터넷 없이도 이미 등록된 아동인지 대조합니다. 사진은 포함되지 않습니다.',
           'Choose the <b>아동마스터.csv</b> you received from HQ. It is stored on this device and used to check duplicates offline. Photos are not included.'],
  impPick:['CSV 파일 고르기','Choose a CSV file'],
  impDone:['%n명을 불러왔습니다.','Loaded %n children.'],
  impFail:['CSV를 읽지 못했습니다. 현지어이름·생년월일 열이 있는 파일인지 확인하세요.',
           'Could not read the CSV. Check that it has 현지어이름 and 생년월일 columns.'],
  impCols:['필요한 열: 아동코드, 현지어이름, 생년월일, 성별 (사업장코드는 있으면 함께 씁니다)',
           'Required columns: 아동코드, 현지어이름, 생년월일, 성별 (사업장코드 is used when present)'],

  /* ── 사진 자동 점검 ── */
  qcChecking:['사진을 확인하는 중…','Checking the photo…'],
  qcOk:['자동 점검을 통과했습니다','Automatic checks passed'],
  qcWarnTitle:['확인해 주세요','Worth a look'],
  qcBadTitle:['다시 찍기를 권합니다','Better to retake this'],
  qcRetake:['다시 찍기','Retake'],
  qcAccept:['이대로 사용','Use anyway'],
  qcAccepted:['담당자가 확인하고 그대로 사용했습니다.','Checked and kept by the staff member.'],
  qcBlocked:['사진을 다시 찍거나, 확인 후 [이대로 사용]을 눌러주세요.',
             'Retake the photo, or check it and tap [Use anyway].'],
  qcPrivacy:['점검은 휴대폰 안에서만 이뤄지며 사진은 전송되지 않습니다. 자동 판정이 틀릴 수 있으니 눈으로 한 번 더 봐주세요.',
             'Checks run on this phone and no photo is sent anywhere. The result can be wrong — trust your own eyes too.'],
  qc_blur_bad:['흔들렸거나 초점이 나갔습니다.','Blurred or out of focus.'],
  qc_blur_warn:['조금 흔들렸습니다.','Slightly blurred.'],
  qc_lowcontrast:['화면에 아무것도 잡히지 않았습니다. 렌즈가 가려졌는지 확인하세요.',
                  'Nothing is visible. Check that the lens is not covered.'],
  qc_dark_bad:['너무 어둡습니다. 밝은 곳으로 옮겨서 찍어주세요.','Too dark. Move somewhere brighter.'],
  qc_dark_warn:['조금 어둡습니다.','A little dark.'],
  qc_bright_warn:['너무 밝아 얼굴이 하얗게 날아갔을 수 있습니다.','Very bright — the face may be washed out.'],
  qc_backlit_bad:['역광입니다. 해를 등지지 말고 그늘에서 찍어주세요.',
                  'Backlit. Move into shade instead of shooting towards the sun.'],
  qc_backlit_warn:['역광 기미가 있습니다. 배경이 아동보다 훨씬 밝습니다.',
                   'Slightly backlit — the background is much brighter than the child.'],
  qc_noface:['얼굴을 찾지 못했습니다. 정면으로 밝게 찍혔는지 확인하세요. (옆얼굴이나 그늘진 얼굴은 못 찾을 수 있습니다)',
             'No face found. Check it is front-on and well lit. (Side or shadowed faces are often missed.)'],
  qc_noengine:['얼굴 확인 기능을 불러오지 못했습니다. 사진은 그대로 사용할 수 있습니다.',
               'The face check could not load. The photo can still be used.'],
  qc_manyfaces:['얼굴이 여럿 보입니다. 아동 혼자 나와야 합니다.','More than one face. The child should be alone.'],
  qc_far:['아동이 너무 멀리 있습니다. 상반신이 화면에 차도록 다가가세요.',
          'The child is too far away. Come closer so the upper body fills the frame.'],
  qc_close:['너무 가깝습니다. 어깨까지 보이도록 조금 물러나세요.',
            'Too close. Step back so the shoulders are visible.'],
  qc_croptop:['머리 윗부분이 잘렸습니다.','The top of the head is cut off.'],
  qc_cropside:['얼굴이 화면 밖으로 잘렸습니다.','The face is cut off at the edge of the frame.'],
  qc_offcenter:['아동이 화면 가운데에 오도록 맞춰주세요.','Center the child in the frame.'],
  photoFail:['사진을 읽지 못했습니다. 다시 찍어주세요.','Could not read the photo. Please take it again.'],

  /* ── 본부 전송 ── */
  hqUrl:['본부 전송 주소 (선택)','HQ sync address (optional)'],
  hqUrlHint:['본부에서 받은 Apps Script 주소를 붙여넣으세요. 비워두면 전송 없이 내보내기만 씁니다.',
             'Paste the Apps Script address from HQ. Leave empty to use manual export only.'],
  hqKey:['전송키','Sync key'],
  hqKeyPh:['본부에서 받은 키','Key from HQ'],
  hqTest:['연결 확인','Test connection'],
  hqTesting:['확인하는 중…','Testing…'],
  hqOk:['본부와 연결됩니다.','Connected to HQ.'],
  hqFail:['연결하지 못했습니다.','Could not connect.'],
  hqNoUrl:['주소를 먼저 넣어주세요.','Enter the address first.'],
  homeLede:['등록은 인터넷 없이 진행됩니다. 아동코드는 본부에서 부여합니다.',
            'Registration works offline. Child codes are assigned by HQ.'],
  codePending:['본부 부여 대기','Awaiting HQ'],
  statUnsent:['미전송','Not sent'],
  tagSent:['전송됨','Sent'],
  tagWaiting:['전송대기','Waiting'],
  syncBtn:['본부로 전송 (%n건)','Send to HQ (%n)'],
  syncing:['전송 중…','Sending…'],
  syncProgress:['전송 중 %i / %n','Sending %i of %n'],
  syncDone:['%n건을 본부로 보냈습니다. 아동코드가 부여되었습니다.',
            'Sent %n to HQ. Child codes have been assigned.'],
  syncPartial:['%s건 전송, %f건 실패. 연결되면 자동으로 다시 시도합니다.',
               '%s sent, %f failed. It will retry automatically when connected.'],
  syncNothing:['보낼 등록이 없습니다.','Nothing to send.'],
  syncOffline:['인터넷에 연결되면 자동으로 전송됩니다.','It will send automatically once you are online.'],
  lastSync:['마지막 전송 %d','Last sent %d'],
  noHqUrl:['본부 전송 주소가 없어 내보내기로만 취합됩니다.',
           'No HQ address set — data is collected by manual export only.'],
  savedLocal:['%n 등록을 저장했습니다.','Saved the registration for %n.'],

  backupTitle:['백업 파일 내려받기','Download a backup'],
  backupLede:['전송이 안 되는 상황을 대비한 보조 수단입니다. 평소에는 [본부로 전송]만 쓰면 됩니다.',
              'A fallback for when uploading is not possible. Normally just use [Send to HQ].'],

  /* ── 관리자 페이지 ── */
  adminBtn:['관리자 페이지','Admin settings'],
  adminTitle:['관리자 설정','Admin settings'],
  adminEyebrow:['본부 전용','Administrator'],
  adminPinAsk:['관리자 비밀번호를 입력하세요.','Enter the admin password.'],
  adminPin:['관리자 비밀번호','Admin password'],
  adminEnter:['들어가기','Enter'],
  adminWrong:['비밀번호가 맞지 않습니다.','That password is not correct.'],
  adminLock:['잠그고 나가기','Lock and exit'],
  adminSaved:['설정을 저장했습니다.','Settings saved.'],
  adminNote:['이 설정은 이 기기에만 적용됩니다. 다른 기기에도 똑같이 적용하려면 아래 [설정 파일 내보내기]로 파일을 만들어 전달하세요.',
             'These settings apply to this device only. To apply them elsewhere, export the file below and share it.'],

  tabPlace:['국가·사업장','Countries and sites'],
  tabField:['등록 항목','Fields'],
  tabEtc:['관리','Maintenance'],

  cList:['국가 목록','Countries'],
  sList:['사업장 목록','Field offices'],
  inUse:['사용','On'],
  notUse:['사용 안 함','Off'],
  addCountry:['＋ 국가 추가','＋ Add a country'],
  addSite:['＋ 사업장 추가','＋ Add a field office'],
  fCode:['코드','Code'],
  fCodeHint:['영문 대문자 3글자를 권합니다. 아동코드에 그대로 들어갑니다.',
             'Three capital letters is best. It becomes part of the child code.'],
  fKo:['한글 이름','Korean name'],
  fEn:['영문 이름','English name'],
  fCountry:['소속 국가','Country'],
  addOk:['추가','Add'],
  cancel:['취소','Cancel'],
  addedMark:['추가함','Added'],
  removeItem:['삭제','Delete'],
  errCode:['코드는 영문 2~4글자로 입력하세요.','Use 2 to 4 letters for the code.'],
  errDupCode:['이미 있는 코드입니다.','That code already exists.'],
  errName:['이름을 입력하세요.','Enter a name.'],
  cantRemove:['이미 등록에 사용된 항목은 지울 수 없습니다. [사용 안 함]으로 바꾸세요.',
              'This is already used by a registration. Switch it off instead.'],
  offWarn:['현재 선택된 사업장을 사용 안 함으로 바꿨습니다. 설정 화면에서 다시 골라주세요.',
           'You switched off the site currently in use. Choose another in settings.'],

  fieldLede:['각 항목을 필수·선택·사용 안 함 중에서 고르세요. 아동 식별과 아동보호에 필요한 항목은 끌 수 없어 목록에 없습니다.',
             'Set each field to required, optional or off. Fields needed for identification and safeguarding cannot be switched off, so they are not listed.'],
  fReq:['필수','Required'],
  fOpt:['선택','Optional'],
  fOff:['사용 안 함','Off'],
  lockedTitle:['끌 수 없는 항목','Always on'],
  lockedList:['영문 이름 · 생년월일 · 성별 · 상반신 사진 · 촬영 기준 확인 · 보호자와 아동 동의',
              'Name in English · date of birth · sex · upper-body photo · photo standards · guardian and child consent'],

  cfgExport:['설정 파일 내보내기','Export settings file'],
  cfgImport:['설정 파일 불러오기','Import settings file'],
  cfgImported:['설정을 불러왔습니다.','Settings imported.'],
  cfgBad:['설정 파일이 아닙니다.','That is not a settings file.'],
  cfgReset:['설정 초기화','Reset settings'],
  cfgResetAsk:['모든 관리자 설정을 처음 상태로 되돌립니다. 등록된 아동 자료는 지워지지 않습니다.',
               'Returns every admin setting to its original state. Registered children are not deleted.'],
  cfgResetOk:['설정을 초기화했습니다.','Settings reset.'],
  pinChange:['관리자 비밀번호 변경','Change the admin password'],
  pinNew:['새 비밀번호','New password'],
  pinSaved:['비밀번호를 바꿨습니다.','Password changed.'],
  pinShort:['4자 이상으로 정해주세요.','Use at least 4 characters.'],

  /* ── 본부 설정 배포 ── */
  pubTitle:['전 기기에 적용','Apply to every device'],
  pubBody:['지금 설정을 본부에 저장합니다. 각 직원 휴대폰이 다음 전송 때 자동으로 받아갑니다. 직원이 따로 할 일은 없습니다.',
           'Saves these settings to HQ. Every staff phone picks them up on its next upload. Staff do not need to do anything.'],
  pubBtn:['본부에 저장하고 적용','Save to HQ and apply'],
  pubAsk:['관리자 비밀번호를 한 번 더 입력하세요.','Enter the admin password once more.'],
  pubDone:['본부에 저장했습니다. 각 기기가 다음 전송 때 받아갑니다. (개정 %n)',
           'Saved to HQ. Devices will pick it up on their next upload. (revision %n)'],
  pubFail:['본부에 저장하지 못했습니다: %e','Could not save to HQ: %e'],
  pubNoUrl:['본부 전송 주소가 없어 이 기기에만 적용됩니다.',
            'No HQ address is set, so this applies to this device only.'],
  pullBtn:['본부 설정 다시 받기','Fetch HQ settings again'],
  pullDone:['본부 설정을 받았습니다.','HQ settings applied.'],
  pullSame:['이미 최신입니다.','Already up to date.'],
  revNow:['현재 개정 %n','Revision %n'],
  fromHq:['본부에서 내려온 설정입니다. 여기서 고친 뒤 [본부에 저장하고 적용]을 눌러야 다른 기기에 전달됩니다.',
          'These came from HQ. After editing, tap [Save to HQ and apply] to send them to the other devices.']
};